### ISSUE TITLE
No warning if textarea has focus

### ISSUE THREAD

**Issue by urbalazs** [reneeb/otrs-WarnMissingAttachment#1]
There is no warning, if the user wrote the message, leaves the cursor (focus) on the textarea, and clicks the "Submit" button. If the user clicks outside the texarea (it lost the focus), then clicking the "Submit" button appears the dialog.
Same situation is, when a user mentioned an attachment word, clicked the button, got the warning message, then went back to textarea, deleted the attachment word, and clicking the button will show the dialog again. If the user clicks outside the texarea (it lost the focus), then clicking the "Submit" button, there is no warning dialog.

So the problem is, that [this line](https://github.com/reneeb/otrs-WarnMissingAttachment/blob/master/Kernel/Output/HTML/Templates/Standard/WarnMissingAttachmentJS.tt#L50) doesn't work:
`$('textarea[name="[% Data.Fieldname | html %]"]').trigger('change');`

I tried the following (also not works):
`$('textarea[name="[% Data.Fieldname | html %]"]').change();`
`$('textarea[name="[% Data.Fieldname | html %]"]').trigger('blur');`
`$('textarea[name="[% Data.Fieldname | html %]"]').blur();`

**Comment by reneeb** [comment]
Which browser and which OS do you use? I've tested it with Firefox on Linux and it works. I will test it with Firefox and IE on Windows 8 this evening...

**Comment by urbalazs** [comment]
Hi @reneeb 
I'm using Firefox on Linux, too. We tested it on Ubuntu 16.04 and Ubuntu Gnome 16.04 with Firefox 45.

How to reproduce the bug:
1.) Create a new Phone ticket
2.) Click in the textarea, write: "attach"
3.) Click "Submit"
No WarnMissingAttachment dialog, but OTRS errors because of the missing mandatory fields.

Again:
1.) Create a new Phone ticket
2.) Click in the textarea, write: "attach"
**3.) Click out from textarea (somewhere in the page)**
4.) Click "Submit"
A WarnMissingAttachment dialog appears, then the OTRS errors because of the missing mandatory fields.

If you fill the mandatory fields, in the first case the ticket will be created without attachment and without warnings about missing attachment. In the second case there is a WarnMissingAttachment dialog before creating the ticket.

Can you confirm, or shall I make a screencast?

**Comment by reneeb** [comment]
Ah, ok... got it...

**Comment by reneeb** [comment]
@urbalazs Please test v5.0.2 - should arrive on OPAR in a few minutes...

**Comment by urbalazs** [comment]
It works, thank you! You can close this issue.

p.s.: don't forget to finish the German translation, there are a few new strings in the language file.

**Comment by reneeb** [comment]
Thanks...
